import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import NavLogo from "@/Components/Navbar/Logo";
import { playfair, sofia } from "@/utils/fonts";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${playfair.variable} ${sofia.variable}`}
		>
			<body>
				<Navbar>
					<NavLogo />
				</Navbar>
				{children}
			</body>
		</html>
	);
}
